In [1]:
# 최적화 연산 그래프 정의

import torch

x = torch.ones(5) # input tensor
y = torch.zeros(3) # expected output tensor
w = torch.randn(5, 3, requires_grad = True)
b = torch.randn(3, requires_grad = True)
z = torch.matmul(x, w) + b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

In [ ]:
# Gradient 계산
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.0346, 0.1696, 0.0618],
        [0.0346, 0.1696, 0.0618],
        [0.0346, 0.1696, 0.0618],
        [0.0346, 0.1696, 0.0618],
        [0.0346, 0.1696, 0.0618]])
tensor([0.0346, 0.1696, 0.0618])


In [ ]:
# 변화도 추적 멈추기
z = torch.matmul(x,w) + b
print(z.requires_grad)  # True

with torch.no_grad():
    z = torch.matmul(x,w) + b
print(z.requires_grad)  # False

True
False


In [ ]:
# 변화도 추적 멈추기 2
z = torch.matmul(x, w)+b
z_det = z.detach()
print(z_det.requires_grad)

False


In [5]:
# 텐서 변화도와 야코비안 곱
inp = torch.eye(4,5, requires_grad=True)
out = (inp + 1).pow(2).t()

out.backward(torch.ones_like(out), retain_graph=True)
print(f"First call\n{inp.grad}")

out.backward(torch.ones_like(out), retain_graph=True)
print(f"\nSecond call\n{inp.grad}")

inp.grad.zero_()
out.backward(torch.ones_like(out), retain_graph=True)
print(f"\nCall after zeroing gradients\n{inp.grad}")

First call
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])

Second call
tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.]])

Call after zeroing gradients
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])
